# Generated by Django 5.2.5 on 2025-09-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='founder_images/'),
        ),
        migrations.AddField(
            model_name='founder',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='startup_images/'),
        ),
        migrations.AddField(
            model_name='startup',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
