# Generated by Django 5.2.5 on 2025-09-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_founder_image_founder_image_url_startup_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='founder',
            name='image',
        ),
        migrations.RemoveField(
            model_name='founder',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='jebuser',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='jebuser',
            name='profile_image_url',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='image',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='image_url',
        ),
    ]
