# Generated by Django 5.2.5 on 2025-09-09 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_image_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_funding', models.CharField(blank=True, max_length=100)),
                ('target_funding', models.CharField(blank=True, max_length=100)),
                ('revenue', models.CharField(blank=True, max_length=100)),
                ('projected_revenue', models.CharField(blank=True, max_length=100)),
                ('users', models.IntegerField(default=0)),
                ('growth', models.CharField(blank=True, max_length=100)),
                ('market_size', models.CharField(blank=True, max_length=100)),
                ('advantages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_deck', to='api.startup')),
            ],
        ),
    ]
