# Generated by Django 4.2.7 on 2026-01-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='action_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='area',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='area',
            name='reaction_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
